### ISSUE TITLE
Swaps Overwrite Forced Bar Changes

### ISSUE THREAD

**Issue by Diorik** [zacharied/FFXIV-Plugin-HudManager#1]
Whenever the game changes your main hotbar (such as hacking minigame in Tower, Pomander of Rage, getting in a mech in Rival Wings, controlling other NPCs in event scenarios) HudMan realizes your bars changed and attempts to apply swaps, hiding the new bar crippling you (buttons available on the pet bar still, but not ideal). Doesn't apply to mounts with special actions, but virtually everything else. 

It would be great if HudMan had a condition for this state so that the buttons aren't lost and we could have a special layout for it, if such a state can be tested for, but at least it should stop murdering the new bar. If nothing else, there could be an option to disable swaps without a concrete inciting event like class, info, or area change.

**Comment by zacharied** [comment]
I think I get what you're referring to. To be clear, I'm assuming this is happening because you have your "combat" UI set to display when you have your weapon drawn, and in these places the game interprets your weapon as not being drawn?

There's a few more conditions that I should add. For the time being, you can add another swap condition for Roleplaying, which will handle the cases for when you are controlling a different character.

I'll work on adding an "advanced mode" for the conditions interface that will show all conditions exposed by Dalamud. This should help for the time being until I unlock all the content that these cases happen in.

**Comment by Diorik** [comment]
No, I only have swaps based on my active class. It looks like HudMan simply realizes that my Hud updated and it needs to re-apply the swap logic stack, which ends in swapping out the new special bar.

**Comment by zacharied** [comment]
OK, would you mind going to `%AppData%\Roaming\XIVLauncher\pluginConfigs` and sending the HUDManager.json file in there?

**Comment by zacharied** [comment]
Technical summary: when the pet hotbar is active (such as in the situations listed in OP), the game copies the contents of that bar to your Hotbar 1, based on a setting in Character Config (I believe it's called Auto-Show Pet Hotbar). Whenever a HUD change is made (that is, calling the game's internal `UpdateHUD` function), the contents of that hotbar are restored to their original job contents.

Possible solutions that I can come up with would rely on hooking into the game and either forcing a redraw of the Hotbar 1. (this can be accomplished manually by changing the "Auto-Show Pet Hotbar" to option 2 and then back to option 1 or 3). This could be accomplished by manually forcing a change of that setting (although I've had difficulty getting the Dalamud internal setting API to work), or hooking deeper and manually calling the function that first replaces Hotbar 1 with the Pet Hotbar contents. Depending on how the game is coded, there might be a function call that returns the original hotbar contents that we could disable.

Mitigated as of 6e8fd625b11faf672c8479b840916a718a76afac. There is a toggle setting that will prevent any modification of the HUD while the Pet Hotbar is active. However, the ideal solution would still allow for HUD manipulation.

**Comment by zacharied** [comment]
Fixed completely by 85b464c5d5b09025d5048b40bb54e2dd61ea5a4d.
