### ISSUE TITLE
HUDManager Error

### ISSUE THREAD

**Issue by NSandro** [zacharied/FFXIV-Plugin-HudManager#10]
Hello. I got error when i try to choice layout.
![ffxiv_dx11_GFHF0uHyUK](https://user-images.githubusercontent.com/100220878/155167990-8ffaf1a1-a9cc-49e4-afa7-10571005c8e4.png)

I have removed lot of other plugin. but got always this error.

**Comment by NSandro** [comment]
Ok i found why...i playing in french client....

**Comment by zacharied** [comment]
Fixed by 8803b98958cab3a4ff21b70edb3c28c5d69125fc .+
