### ISSUE TITLE
[Request] Keybinds Attached to Layouts

### ISSUE THREAD

**Issue by Diorik** [zacharied/FFXIV-Plugin-HudManager#2]
If feasible and considered within scope of the project, it would be excellent if keybinds could be included in saved layouts, just to cite a use case I'd use different behinds for DoL classes if I could.

**Comment by zacharied** [comment]
Unfortunately working with the game's keybinding code is pretty awful from what I've heard, and would probably require too much additional work for something I wouldn't use myself. I'll keep this idea in the back of my mind in case more discoveries are made regarding how the game handles keybind assignment, but I wouldn't hold my breath for it.
