### ISSUE TITLE
[Testing Bug] In Custom Conditions menu, priority arrow buttons bugs.

### ISSUE THREAD

**Issue by johnysandels** [zacharied/FFXIV-Plugin-HudManager#21]
Only the down arrow works for shifting condition priority. up arrow doesn't do anything.

Pressing the down arrow on the bottom condition crashes the plugin.

~~Suggestion:
Allow changing Condition name on creation, instead of defaulting to `Condition[#]`~~  moved to #22

**Comment by zacharied** [comment]
Sorry, was on vacation the past week. I'll try to get on this when I can.

Regarding the suggestion, I've created a new issue for it at #22.

**Comment by zacharied** [comment]
Fixed as of 328f5c0c573c58df16e1f051266b964d83a745bc.
