### ISSUE TITLE
[Suggestion] Command to disable swaps

### ISSUE THREAD

**Issue by simonebarbieri** [zacharied/FFXIV-Plugin-HudManager#28]
Hello! Would it be possible to have a command to enable/disable the swaps? It would be great for macros. 

For instance, I have a `default` layout, with everything enabled, and an `immersive` layout, with a lot of stuff disabled. Usually I keep the `immersive`, and I have set up conditions for when I enter in combat, etc.
Sometimes, however, I need to enable all the UI (for setup, maybe, as the `default` layout is the highest in hierarchy, or any other reason), and I've prepared a macro to activate it. When a condition triggers, though, it brings back the other layouts, and in the end goes back to `immersive`, which is the layout it sets when no other condition is met! The command to disable the swaps would be great in these kinds of situations!

Thank you for your work :)

**Comment by zacharied** [comment]
Reasonable suggestion, and easy to implement. I'll put it in the next update.

**Comment by zacharied** [comment]
Implemented in 6e79d5086baa39d48abaefb9fee8a4d3f7d6f43c.
