### ISSUE TITLE
[Suggestion] A few suggestions

### ISSUE THREAD

**Issue by Adam-M93** [zacharied/FFXIV-Plugin-HudManager#30]
I've been using HUD Manager for a while and have loved it, it's been great for getting my HUD almost exactly how I want. I've got a few idea suggestions though if they're possible. 
I didn't want to post a new issue for each one and cause spam, sorry if I should have, also wasn't sure what to put for the title

Extra Conditions
- Condition for when in Gamepad Mode/Mouse Mode
- Condition for level (e.g. If level X or under) so you could set up layouts for when you don't have your job bar
- Condition for when a pet (Carbuncle, Selene, etc) is summoned

Layout
- Allow using the Windows option in the Layout Editor to position and scale the Recommendations window for the selected layout

Profiles
- Allow setting up profiles with multiple conditions/layouts, that you can swap between using macros (similar to how you can with custom conditions). Such as a profile with smaller UI parts and different positions to better fit the Steam Deck's smaller screen. Or a profile with positions and larger UI parts for when playing on a big TV

**Comment by zacharied** [comment]
Thanks for the suggestions! No worries about the big message, I'll split it up into a couple different issues for easier tracking.

Gamepad/mouse mode: implemented in 7661e9e3a92bcf3726e758c725bb05f8b30be41a.
Level conditions: #33.
Pet/summon conditions: #11.

Recommendations window: implemented in 1ffaebbee859424fbcebc839210441c6ba5b2793.

Profiles: #12.

I'll be closing this issue but you can track any progress for this stuff in the issues I mentioned.
