### ISSUE TITLE
Frame drops whenever a potential swap condition is achieved

### ISSUE THREAD

**Issue by turtlehero** [zacharied/FFXIV-Plugin-HudManager#31]
whenever you meet one of the potential state requirements for a swap (ie: drawing weapon, mounting, leaving sanctuary, swapping job, starting to craft, etc) the frame rate will drop. this is EVEN WHEN you do NOT have those as states it should be checking for.

another thing is if we are not doing anything crazy with our UI, can we have a simplified version to just use the swaphud command in game? ie: /hudlayout 1 or /hudlayout 2. just swap the hud layout, none of this constant rearranging. a lightweight setting would relieve lots of frame drops as swapping hud layout this way has no impact on performance.

**Comment by zacharied** [comment]
For the stuttering, are you using XIVAlexander? That is known to cause stuttering issues.

For the second issue, swapping in that manner is already possible. From the plugin help,

`/hudman swap <layout> → switch to a layout`

It should be as simple as `/hudman swap 1` to swap layouts in the manner you describe.

**Comment by turtlehero** [comment]
there is already a command in game to swap hudlayouts, idea for me of that plugin is automation. i can remove xivalex and see if i get the same frame drops.

**Comment by zacharied** [comment]
I think there was some confusion here regarding the command.

`/hudman swap` works via HUDManager layout names. So if you have a layout called "Combat", you can switch to it with `/hudman swap Combat`.

**Comment by turtlehero** [comment]
Yea so im talking a simplified auto swap mode. instead of relying on the custom UI setup (which is confusing AF by the way. i also dont think the visiblity toggle does anything? or no setting to apply changes that i could easily find. the help article regarding that does not really fix it.), have a simple mode that just goes "in so and so situation, swap to in game saved hud layout 1, 2, 3, 4" not needing a staging slot or anything. In other testing, alex xiv was the cause of all the stuttering, might want to put a note in the Help tab of the menu for that. it was unbearable before.Sent from my iPhoneOn Apr 27, 2022, at 5:33 PM, Zach Day ***@***.***> wrote:I think there was some confusion here regarding the command./hudman swap works via HUDManager layout names. So if you have a layout called "Combat", you can switch to it with /hudman swap Combat.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by turtlehero** [comment]
You have to click the KEYBOARD or MOUSE!?!?!?!? i figured unchecking visibility under the tab "enabled" would just nuke it. that is crazy unclear and there is no hover text to explain thatSent from my iPhoneOn Apr 27, 2022, at 5:57 PM, Zach Day ***@***.***> wrote:I understand your suggestion now, thanks for the patience. I'll consider implementing it, but it won't be a priority for a while. I do see how the plugin's interface can be confusing; unfortunately it's not easy to make a simple interface for something as complicated as this.In regards to your specific issue, there's no setting to apply changes in the layout editor because the changes are applied immediately. I can confirm the visibility toggle works fine, see the attached video. If there's a specific element for which the toggle isn't working, let me know which one so I can investigate.https://user-images.githubusercontent.com/6374275/165644605-4bc368bc-c7eb-4b44-a6f9-ffaff4bf90b5.mp4—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by zacharied** [comment]
Ok, might add some hover text or something. I think we're done here so I'm closing the issue.

**Comment by zacharied** [comment]
Split into #32.
