### ISSUE TITLE
[Question] Custom Condition for 'not in instance'

### ISSUE THREAD

**Issue by gucciBane** [zacharied/FFXIV-Plugin-HudManager#36]
Hey,

I'm trying to make a layer for Not In Instance ("Outside") to reset what the In Instance layer above it is doing (in picture). The condition set for Outside doesn't seem to be working, though. Am I misunderstanding the Custom Conditions setup?

![conditions](https://user-images.githubusercontent.com/49180180/166106916-34ef4440-86e1-49dd-bb0b-63696fbe0e42.png)

Thanks

**Comment by zacharied** [comment]
Yeah, I think the negation feature is actually borked entirely. I'll be pushing out a fix soon.

**Comment by zacharied** [comment]
Fixed in 0f24f32537642669b15ac7de7f36380a7e9b84ba.
