### ISSUE TITLE
[Request] Add Crystalline Conflict Ally/Enemy Info Windows

### ISSUE THREAD

**Issue by Toora** [zacharied/FFXIV-Plugin-HudManager#37]
They are currently missing in the list, while the old The Feast ones are still there.

Is there a way to add them manually?

**Comment by zacharied** [comment]
Not at the moment. I mentioned this in an earlier patchnote but the game handles CC elements slightly differently than normal UI elements, preventing HUDManager from manipulating it with the current method we use (this is the same issue as the Ocean Fishing panel, IIRC).

I don't play much PvP so fixing it is not really a priority for me. I'll gladly accept any contributions that fix it, though.

**Comment by Toora** [comment]
Seems I missed those notes, apologies. No worries.
