### ISSUE TITLE
Minimap zoom and main hotbar reset whenever swap conditions occur

### ISSUE THREAD

**Issue by NuckChorris** [zacharied/FFXIV-Plugin-HudManager#39]
Love this plugin so much, it's made my life a lot easier switching between many jobs, but it has one massive bug that keeps me toggling it pretty frequently...

Whenever a swap condition changes, even if it doesn't trigger a swap, ephemeral HUD state is reset. The main symptoms seem to be that your main hotbar and minimap zoom to be reset to the defaults, but there may be other stateful elements I haven't noticed.

**Comment by zacharied** [comment]
When you say that it "resets the main hotbar" what do you mean? I'm assuming you mean that it wipes special mount actions and such, but just wanna make sure I'm understanding the problem.

**Comment by NuckChorris** [comment]
![image](https://user-images.githubusercontent.com/430411/172036656-af2e1078-cf93-43da-9f35-fbfbb4621532.png)

Sorry, I wasn't super clear! I'm referring to how Hotbar 1 (the one that's on `1234567890-=` by default) is swappable with the little up/down arrows on the left or via `/hotbar change [number]`. If this is changed to anything except `1` it'll be reset to `1` when the condition changes.

**Comment by zacharied** [comment]
Oh, I see, thanks for clarifying. Never noticed since I haven't used that feature, but I can definitely poke around and see if it's easily fixable.

**Comment by V3semir** [comment]
Happens to me as well, in my case the Hotbar 1, and Main Menu bar resets to default position every time I swap layouts.

**Comment by nebel** [comment]
This should be fixed as of 2.5.16.0. Please let me know if it is not.
