### ISSUE TITLE
"This plugin failed to load"

### ISSUE THREAD

**Issue by Ellakai** [zacharied/FFXIV-Plugin-HudManager#44]
Dear team,

Thanks for your work :) it's very great :)
I have an issue with your last version (2.5.6.4). Plugin failed to load.
One update is it necessary ?

thanks

![Capture d’écran 2022-07-24 095007](https://user-images.githubusercontent.com/109894709/180637640-4558b576-b243-4448-a761-1bd7eaca0077.gif)

**Comment by zacharied** [comment]
I've seen a couple of other people report crashes as well. I'll take a look into it today.

**Comment by Ellakai** [comment]
ok thanks for your work :)

If you need something (log, dalamud version, ...) don't hesitate to ask :)
