### ISSUE TITLE
[Bug] Export Layout to HUD slot logging is shifted by one

### ISSUE THREAD

**Issue by ccp6128** [zacharied/FFXIV-Plugin-HudManager#46]
Reproduction :

Use the Export Layout to In-game Hud Feature.

I clicked on the 4 buttons in order (1 to 4) and here is the output I got in console :

![image](https://user-images.githubusercontent.com/39601877/183703417-012f5070-12b9-4039-8b7d-5961d68297d9.png)

I confirmed that the layout is properly saved to the right HUD slot. However, the log text in the console is shifted by one

**Comment by nebel** [comment]
Should be fixed in recent versions. Please open a new issue if you can still see this happening.
