### ISSUE TITLE
Pvp condition issues

### ISSUE THREAD

**Issue by Delaene** [zacharied/FFXIV-Plugin-HudManager#49]
It seems the Pvp condition for preset swapping is not working.
I've set up an "idle" preset, an "in combat" preset and an "in pvp" preset but i can't get it to activate while in Wolves' Den and during Crystalling Conflict matches.
Is it intended to work only during frontlines? If so can it be made working in WD and CC matches?

**Comment by zacharied** [comment]
I'll take a look when I get a chance. I'm guessing the detection method got broken by an XIV update at some point. Shouldn't be too hard to fix.
