### ISSUE TITLE
[Suggestion] Add "is NPC dialogue window on-screen" as a swap condition

### ISSUE THREAD

**Issue by andreycout** [zacharied/FFXIV-Plugin-HudManager#5]
As the title implies, it would be nice to have such a swap condition available for when talking to a NPC, allowing us to make all the HUD (except the dialogue window itself) disappear while talking to NPCs and reading the text. Makes it less distracting and more immersive. There's an in-game way of doing this by pressing the sub-command button (square by default) while there's dialogue on-screen, but you have to press it again every time a new dialogue window opens.

**Comment by zacharied** [comment]
Fixed in 49fe7d5.

Thanks for the suggestion!
