### ISSUE TITLE
Wrong number displayed in log when importing layout.

### ISSUE THREAD

**Issue by aradiel** [zacharied/FFXIV-Plugin-HudManager#52]
When importing the layout from the in-game HUD editor, the plugin will display "Two", "Three", "Four" and "4" respectively when logging on the chat.

![image](https://user-images.githubusercontent.com/106691810/195722174-403492ed-06e5-4a70-95e4-d5abde6e090a.png)

**Comment by nebel** [comment]
I believe this should be fixed as of the most recent version. Please open a new issue if this problem happens again.
