### ISSUE TITLE
Update for 6.3

### ISSUE THREAD

**Issue by Avalon304** [zacharied/FFXIV-Plugin-HudManager#56]
Plugins no longer working in patch 6.3

**Comment by Delaene** [comment]
Really looking forward to this too, this plugin is the main reason i have testing enabled in dalamud :D can't wait for it to reach a stable status

**Comment by Diorik** [comment]
My exported HUDs were messed up and I am dying for the fix.

**Comment by zacharied** [comment]
Fixed!
