### ISSUE TITLE
Layout not saving & disappears when importing from clipboard

### ISSUE THREAD

**Issue by Whiiskeyz** [zacharied/FFXIV-Plugin-HudManager#6]
As the title says, every time I import a preset through clipboard, I attempt to name the layout and override a HUD Layout with the new one then select the newly created one but no changes are made. If I close and re-open HUD Manager then go back into the layout section, the layout that was just made disappears completely. I've tried uninstalling and reinstalling the plugin/relogging or even deleting the HUD Manager file within XIV Launcher.

**Comment by zacharied** [comment]
Hi, this is strange. I just tested the import functionality and it worked for me. To clarify, when you go to import a layout, the steps should be:

1. Click the import button
2. Enter the name of the new layout
3. Click the clipboard button

If this is what you're already doing, then I'll have to investigate further, but I just want to confirm that this is what you're doing.

**Comment by Whiiskeyz** [comment]
Hello, yes i found out what the issue was. It was when people were
importing my HUD and I had child profiles setup. I just removed the child
profile and it fixed

**Comment by zacharied** [comment]
I should get around to fixing this at some point.

**Comment by zacharied** [comment]
Fixed (I think?) in fe06de8ab5be7c5cb3727115f46d9e44b8937be2.
