### ISSUE TITLE
"Show with keyboard/joypad" not working properly

### ISSUE THREAD

**Issue by Delaene** [zacharied/FFXIV-Plugin-HudManager#61]
I'm noticing that the job gauges "show with keyboard" and "show with joypad" checkboxes are not behaving correctly.
I play with mouse+keyboard and ALL my jobs gauges show ONLY if joypad is selected.
![image](https://user-images.githubusercontent.com/42815462/213889611-425b94cf-1eb1-4529-89aa-a2475c6bae90.png)
![image](https://user-images.githubusercontent.com/42815462/213889619-aa02f603-f9e6-46a6-9ca0-e982d88ae8d7.png)
![image](https://user-images.githubusercontent.com/42815462/213889621-d3ca5287-edde-4b66-b964-b2d75d005f37.png)

**Comment by zacharied** [comment]
Yikes, my bad for letting that slip through. Will get on that now.

**Comment by zacharied** [comment]
Fixed by 1e82f217ee74c711a160be8f266fe842ec012f66.
