### ISSUE TITLE
[Request] Deactivation timer for swap conditions

### ISSUE THREAD

**Issue by Dasky14** [zacharied/FFXIV-Plugin-HudManager#63]
I would like to have an option for a deactivation delay for swaps. For example when I leave combat, I could keep my UI visible for 5 more seconds afterwards. Or if I have a key set to show UI elements, I don't need to hold it but simply press it once to show for 10 seconds.

This is a feature I loved to have in Fader, but have been missing since I swapped to HudManager as a replacement.

**Comment by zacharied** [comment]
Implemented in 3017be0f5e8db73c09d35ad3d519e83675578f80, should update in Dalamud soon.
