### ISSUE TITLE
Pet hotbar swap in content does not go away when out of state with pet hotbar

### ISSUE THREAD

**Issue by thakyZ** [zacharied/FFXIV-Plugin-HudManager#65]
I noticed the issue of #1 which you implemented the ability to swap to the pet hotbar however, in content like PvP when mounting a mount with one or more actions and then unmounting the hotbar does not go back to its default state. However, it does appear to act like it is on the default state when pressing keys.

**Comment by thakyZ** [comment]
After a bunch of testing, it would seem it doesn't change at times unless the config window is open.

**Comment by nebel** [comment]
I asked thakyZ to share a screenshot of the pet hotbar settings they are using, which they kindly did. This might be useful for reproducing this issue:

![image](https://github.com/zacharied/FFXIV-Plugin-HudManager/assets/9887/0a0b30e4-6f8b-4f00-aed3-e292d718d1b0)
