### ISSUE TITLE
[Suggestion] New Conditions

### ISSUE THREAD

**Issue by andreycout** [zacharied/FFXIV-Plugin-HudManager#7]
Just suggestions for some useful new conditions to be added:

### 1. **Condition Title**: Inside Sanctuary

**Condition Logic**: If the player is at an area the game considers a sanctuary, where you can logout without waiting and get rested bonus EXP, set this condition to ON. Otherwise set it to OFF

**Explanation**: Sanctuaries are usually towns in which battles do not occur. A lot of the HUD elements are useless in such places. The user would be able to create a very minimal HUD preset to use automatically in such locations to better immerse in the game while questing, visiting vendors or just goofing around checking out band performances at the starter cities.

### 2. **Condition Title**: Mounted
**Condition Logic**: Self-explanatory. When in a mount, set it to ON.

**Explanation**: Could be useful to have a specific "voyage" HUD for when getting around with a mount.

### 3. **Condition Title**: Inside FATE Area
**Condition Logic**: If player steps into a FATE Zone, set this condition to ON. Otherwise, set it to OFF.

**Explanation**: Getting inside a FATE Zone can radically change what information is useful for the player. For example, you might want to know what the FATE objective is, but your default layout doesn't have the Duty List on. You might want to check out your parameter bar to see how level the level sync affects your HP. Maybe your default HUD doesn't even have the minimap on, but you happen to bump into a FATE by accident and you may want to see its boundaries. As such, it'd be useful to have swaps for Fates. 
As an addendum, separating this condition in two would also be useful: "Inside FATE Area", for when you're at an FATE area but not necessarily level synced and "Participating FATE" for when that FATE is active and its enemies can attack/be attacked by you.

### 4. **Condition Title**: User Holding Key/Gamepad button

**Condition Logic:** While player is holding [user defined key/gamepad button], set this condition to ON. When player releases [user defined hold key/gamepad button], set this condition to OFF

**Explanation**: extremely versatile. FaderPlugin has such an implementation, although the input options available are fairly limited.

### 5. **Condition Title**: User Toggle Key/Gamepad button

**Condition Logic**: When player presses [user defined key/gamepad button] toggle this condition between ON and OFF.

**Explanation**: extremely versatile as well. Because of how automatic swaps work with this plugin, it doesn't play well with macros for manually toggling and adjusting specific elements of the HUD, as any swap reverts HUD elements to the ones in the preset. There's no way to, for example, use a macro to hide all HUD elements but the minimap, or to switch job gauges to simple mode from then on, because whenever another swap condition kicks in the macro changes are overwritten by the preset. The way it works right now, if you have swaps enabled, you need your conditions to cover every situation, as there's no way to manually change an element quickly without opening the plugin and changing your presets. That adds a lot of development burden for creating conditions for every possible situation, some of which are not viable or hard to implement. This suggested new condition (and the previous one) would change that and allow for user control in situations not covered by conditions.

### 6. **Condition Title**: Chat Focus

**Condition Logic**: When the Chat Windows has focus (such as after any Chat Key Combo is pressed), set this to on. When the chat windows doesn't have the focus, set this to off.

**Explanation**: see FaderPlugin implementation of this. Useful for yeeting the chat window away to out of screen X an Y positions when not in use and getting it back to the default position when you want to type.

### 7. **Condition Title**: HUD Select cursor focus

**Condition Logic**: When the HUD select cursor has focus (the white glove that cycles between HUD elements, on default settings it's activated by pressing Touchpad on PS4/PS5 controller or Back on Xbox 360 controller), set this condition to ON. When it doesn't have focus (the cursor disappears when it doesn't have focus), set it to off.

**Explanation**: Had this idea while testing FaderPlugin condition "Chat Focus". Super useful for gamepad players. You could use this to for example have Scenario Guide, NG+ and Duty List hidden by default, but whenever you want to check, you just have to press the HUD select button and this condition would kick-in and set the cursor to the Scenario Guide at the same time. From my testing, the Scenario Guide is usually the first element to be selected by the HUD select button if it's available, followed by the Chat and then the Duty List. This idea is similar to the User Toggle Button for some use cases, but instead of having the same button set the condition on and off, you'd just check if the HUD Select Cursor has focus and let this handle the swap of stuff instead of messing with input events. If the player wants to toggle all the additional HUD off, it's just a matter of pressing the cancel binding (circle/B by default), doing this makes the game focus out of the HUD Select cursor and, in turn, would set this condition to off, untoggling the swap and hiding stuff. Elegant.

### 8. **Condition Title**: Condition Timeout.

**Condition Logic**: When no other conditions of higher priority than this one have their requirements met after [user selected time], set this condition to ON. If any other condition matches, set it to off.

**Explanation**: See FaderPlugin "Idle" setting. Some very cool stuff can be made with this, such as gradually increasing transparency of HUD elements (and or making them smaller) after some time has passed and the conditions that make them relevant are no longer in place, before toggling them off completely. A good candidate for this would be the parameter bar and Job Gauges when out of combat, or you could just use this between pretty much every swap transition to make them less "instant" and more gradual.

### 9. **Condition Title**: Chat Inactive.

**Condition Logic**: Whenever a chat message is written to the currently active chat tab, set this condition to false for [user selected duration] seconds, after that set it to on.

**Explanation**: Allows yeeting the chat window away for out of screen X and Y coordinates when no new chat messages. Best paired with "Chat Focus" condition to enable seeing the chat on demand. Hiding the chat for inactivity iss one of the most demanded features for the UI for years! Even FFXI had an option to gradually hide the chat after some time when there's no messages. Not only does it help declutter your screen, it also brings your attention to the chat when a new message comes as the chat window appears (helpful for distracted players who forget the chat while focused on gameplay in instances and miss important party messages at critical moments. That's me btw).

**Comment by zacharied** [comment]
Conditions number 1, 2, 3, and 5 have been implemented. Gonna try to split this into separate issues.

**Comment by zacharied** [comment]
Suggestion 4 is in #14, 6 in #15, 7 in #15, 8 in #16, and 9 in #17.
