### ISSUE TITLE
Hotbar flicker

### ISSUE THREAD

**Issue by Denixerianer** [zacharied/FFXIV-Plugin-HudManager#73]
When you open the chat to type something with either "enter" or just clicking in the typebox the hotbars flicker off and on once which is quite headache inducing over time xD Note that this happens when using the visibility setting in HudManager (off) and the visibility setting in DelvUI (i have it set to show when weapon unsheathed).

**Comment by nebel** [comment]
In 2.5.17.0, I added a feature which reduces unnecessary swaps which should help with cases like this. It seems DelvUI and HUD Manager are kind of fighting for visibility here, which is probably not easy to solve. However, in the new version, I added logic to avoid swapping HUDs in cases where the HUD actually doesn't change. This means that just activating the chat box should not cause a HUD swap, for example, unless you actually have a condition which uses chat box activation to perform a swap on purpose.

I'm not sure we'll ever have a perfect solution to this but please let me know if 2.5.17.0 helps.

**Comment by Denixerianer** [comment]
Hello, it doesnt flicker anymore at all now! Thanks a ton.

**Comment by nebel** [comment]
Glad to hear it!
