### ISSUE TITLE
Base classes do not trigger swaps

### ISSUE THREAD

**Issue by Cytraen** [zacharied/FFXIV-Plugin-HudManager#75]
Conjurer, Rogue, Archer, etc. do not satisfy the role-based swap conditions. Enable swaps is on, `EN` language, using v2.5.16.0. Screenshots below show CNJ, DRG, and LNC equipped, but only DRG has the star under "active"
<details>
  <summary>Conjurer</summary>

![cnj](https://github.com/zacharied/FFXIV-Plugin-HudManager/assets/60638768/0aeb0769-34ce-44e3-adb1-6255f9c70529)

</details>
<details>
  <summary>Dragoon</summary>

![drg](https://github.com/zacharied/FFXIV-Plugin-HudManager/assets/60638768/47db7662-38ac-40ee-99c6-2eea96022762)

</details>
<details>
  <summary>Lancer</summary>

![lnc](https://github.com/zacharied/FFXIV-Plugin-HudManager/assets/60638768/5bb135a3-4f44-4a87-8be9-d4c42519331b)

</details>

**Comment by nebel** [comment]
Fixed in 2.5.17.0. Thanks for reporting! Please let me know if any similar issues are still happening and upgrading to 2.5.17.0+.
