### ISSUE TITLE
Party List "Align To Bottom" not configurable, but is saved

### ISSUE THREAD

**Issue by Diorik** [zacharied/FFXIV-Plugin-HudManager#80]
![image](https://github.com/zacharied/FFXIV-Plugin-HudManager/assets/11672296/99a0d370-91f8-4514-85f8-739830203851)

In game party list has a configuration to "Align List to Bottom", this can't be set in HudMan, but it IS saved if you import or add the element with the desired setting. Please expose this configuration in the HudMan UI!

**Comment by nebel** [comment]
Thanks for the report! This issue should be fixed in the most recent release (v2.5.18.4).
