### ISSUE TITLE
[Suggestion] Job Categories for switching

### ISSUE THREAD

**Issue by johnysandels** [zacharied/FFXIV-Plugin-HudManager#9]
In the Job category section it would be nice to have a [ Healer/Ranged DPS/Melee DPS/Tank ] selection, instead of having to create a condition for say, all of the states of all of the healers. 
It would be great for the people who want to have the same HUD layout for all of one type of class type. 

I ran into this difficulty when creating a custom layout or all of my healers, and I needed to create 5 hud swap entries for each healer, and it was the same layout for all of the healers.

**Comment by zacharied** [comment]
Fixed in e2e25ce3744530c0c1d7d95c65b2d8f8c8d9942f.
